ALTER TABLE "users"
RENAME COLUMN "name" TO "display_name";

ALTER TABLE "users"
RENAME COLUMN "password" TO "password_hash";

ALTER TABLE "users"
ADD COLUMN "is_active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "last_login_at" TIMESTAMP(3),
ADD COLUMN "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
